# Generated by Django 4.0.4 on 2022-05-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHoppiness', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='foto',
            field=models.URLField(default=''),
        ),
    ]
