# Generated by Django 4.0.4 on 2022-05-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHoppiness', '0003_comida_precio_happy_hour_comida_precio_regular'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='estrellas',
            field=models.IntegerField(default=0),
        ),
    ]
