# Generated by Django 4.0.4 on 2022-05-29 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHoppiness', '0004_opinion_estrellas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Opinion',
            new_name='Valoracion',
        ),
        migrations.AlterField(
            model_name='comida',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comida',
            name='foto',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comida',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comida',
            name='precio_happy_hour',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='comida',
            name='precio_regular',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
