# Generated by Django 4.0.4 on 2022-05-29 19:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppHoppiness', '0005_rename_opinion_valoracion_alter_comida_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'verbose_name': 'Valoraciones', 'verbose_name_plural': 'Valoraciones'},
        ),
        migrations.AddField(
            model_name='valoracion',
            name='imagen',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='ibu',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='imagen',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='marca',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='porcentaje_alcohol',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='precio_happy_hour',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
        migrations.AlterField(
            model_name='bebida',
            name='precio_regular',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1000.0)]),
        ),
    ]
